# ==============================================================================
# 01_05 — Univariate and cross-trait LD Score Regression
# Curated code-release implementation for the final manuscript.
# MiXeR is intentionally not included in the final analysis.
#
# REQUIREMENTS
#   - Python 3 LDSC installation (bulik/ldsc, Python-3 compatible environment)
#   - 1000 Genomes Phase 3 EUR LD scores and regression weights
#   - Harmonized STEP1C files generated by 01_04_gwas_harmonization.R
#
# This wrapper records the exact commands and launches LDSC via system2().
# ==============================================================================

rm(list = ls())
options(stringsAsFactors = FALSE, scipen = 999)

DATA_ROOT <- Sys.getenv("AFHFPEF_DATA_ROOT", unset = "D:/A/data")
LDSC_ROOT <- Sys.getenv("LDSC_ROOT", unset = "D:/A/ldsc39")
LDSC_PYTHON <- Sys.getenv("LDSC_PYTHON", unset = "python")

IN_DIR <- file.path(DATA_ROOT, "STEP1C_GWAS_HARMONIZED")
OUT_DIR <- file.path(DATA_ROOT, "STEP1D_LDSC")
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

MUNGE <- file.path(LDSC_ROOT, "munge_sumstats.py")
LDSC <- file.path(LDSC_ROOT, "ldsc.py")
if (!file.exists(MUNGE) || !file.exists(LDSC)) stop("LDSC scripts not found. Set LDSC_ROOT.")

# Prefer the standard 1000G Phase3 EUR LD-score prefixes. Override with env vars.
REF_LD <- Sys.getenv(
  "LDSC_REF_LD_CHR",
  unset = file.path(DATA_ROOT, "1000G_Phase3_baselineLD_v2.2_ldscores", "baselineLD.")
)
W_LD <- Sys.getenv(
  "LDSC_WEIGHT_LD_CHR",
  unset = file.path(DATA_ROOT, "1000G_Phase3_weights_hm3_no_MHC", "weights.hm3_noMHC.")
)

traits <- c("AF", "HFpEF", "BMI", "OSA")
files <- setNames(
  file.path(IN_DIR, paste0(traits, "_HapMap3_noMHC_LDSC.tsv.gz")),
  traits
)

# STEP1C filenames may carry descriptive prefixes. Fall back to trait-prefix discovery.
for (tr in traits) {
  if (!file.exists(files[[tr]])) {
    hit <- list.files(IN_DIR, pattern = paste0("^", tr, ".*HapMap3_noMHC_LDSC[.]tsv[.]gz$"), full.names = TRUE)
    if (length(hit) != 1L) stop("Could not uniquely resolve STEP1C file for ", tr)
    files[[tr]] <- hit[[1]]
  }
}

run_cmd <- function(script, args, log_file) {
  cat("\nRUN:", LDSC_PYTHON, script, paste(args, collapse = " "), "\n")
  out <- system2(LDSC_PYTHON, c(script, args), stdout = TRUE, stderr = TRUE)
  writeLines(out, log_file)
  invisible(out)
}

munged <- character(length(traits)); names(munged) <- traits
for (tr in traits) {
  prefix <- file.path(OUT_DIR, paste0(tr, ".munged"))
  munged[[tr]] <- paste0(prefix, ".sumstats.gz")
  run_cmd(
    MUNGE,
    c(
      "--sumstats", shQuote(files[[tr]]),
      "--snp", "SNP", "--a1", "A1", "--a2", "A2",
      "--p", "P", "--N-col", "N",
      "--signed-sumstats", "Z,0",
      "--out", shQuote(prefix)
    ),
    paste0(prefix, ".console.log")
  )
}

# Observed-scale SNP heritability used in the manuscript.
for (tr in traits) {
  prefix <- file.path(OUT_DIR, paste0(tr, ".h2"))
  run_cmd(
    LDSC,
    c(
      "--h2", shQuote(munged[[tr]]),
      "--ref-ld-chr", shQuote(REF_LD),
      "--w-ld-chr", shQuote(W_LD),
      "--out", shQuote(prefix)
    ),
    paste0(prefix, ".console.log")
  )
}

pairs <- combn(traits, 2, simplify = FALSE)
for (pp in pairs) {
  tr1 <- pp[[1]]; tr2 <- pp[[2]]
  prefix <- file.path(OUT_DIR, paste0(tr1, "_", tr2, ".rg"))
  run_cmd(
    LDSC,
    c(
      "--rg", shQuote(paste(munged[[tr1]], munged[[tr2]], sep = ",")),
      "--ref-ld-chr", shQuote(REF_LD),
      "--w-ld-chr", shQuote(W_LD),
      "--out", shQuote(prefix)
    ),
    paste0(prefix, ".console.log")
  )
}

writeLines(capture.output(sessionInfo()), file.path(OUT_DIR, "R_sessionInfo_LDSC_wrapper.txt"))
cat("\nLDSC analysis complete. Output:", OUT_DIR, "\n")
